### ISSUE TITLE
Launchercrash by logging in

### ISSUE THREAD

**Issue by Sephiroth91** [tyrone-sudeium/LaunchXIV#1]
Hello,

I have installed your launcher , but it doesn´t work.   I enter my ID , password and activated the one time password. When I click next, your launcher crashed. Can you fix it?

Best wishes

**Comment by tyrone-sudeium** [comment]
Thanks for the report, I haven't been playing much though (and even less so on macOS), so I'm not sure when I'll get around to looking into this, sorry :(

**Comment by tyrone-sudeium** [comment]
@Sephiroth91 I've made a new release, version 0.2. Can you try that version?

**Comment by Sephiroth91** [comment]
@tyrone-sudeium I have tested the launcher. The launcher works fine , but if I start the game ,
the game language change to english. I want to play in german.
Is it possible to improve the game perfomance by using the launcher? I have 20fps with a GTX970.

**Comment by tyrone-sudeium** [comment]
The game should launch with German if you've got your Mac system set to German... if it's not, oops that's another bug.

As for performance... sorry, no, that's entirely Square Enix's fault 😢

**Comment by tyrone-sudeium** [comment]
Closing this since it apparently doesn't crash any more
